--------------------------------------------------------
--  DDL for View ALL_UT_LIB_VALIDATIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "HUNDISILM"."ALL_UT_LIB_VALIDATIONS" ("LIB_VALIDATION_ID", "LIB_VALIDATION_NAME", "LIB_VALIDATION_CLASS", "LIB_VALIDATION", "CREATED_ON", "CREATED_BY") AS 
  SELECT
    "LIB_VALIDATION_ID" AS "LIB_VALIDATION_ID"
   ,"LIB_VALIDATION_NAME" AS "LIB_VALIDATION_NAME"
   ,"LIB_VALIDATION_CLASS" AS "LIB_VALIDATION_CLASS"
   ,"LIB_VALIDATION" AS "LIB_VALIDATION"
   ,"CREATED_ON" AS "CREATED_ON"
   ,"CREATED_BY" AS "CREATED_BY"
  FROM
    "UT_LIB_VALIDATIONS"
  WITH READ ONLY;

   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_VALIDATIONS"."LIB_VALIDATION_ID" IS 'Library Validation Code Hook identifier';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_VALIDATIONS"."LIB_VALIDATION_NAME" IS 'Code Hook name';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_VALIDATIONS"."LIB_VALIDATION_CLASS" IS 'Implementing Java class name';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_VALIDATIONS"."LIB_VALIDATION" IS 'Code Hook property XML';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_VALIDATIONS"."CREATED_ON" IS 'Creation timestamp';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_VALIDATIONS"."CREATED_BY" IS 'Created by user';
   COMMENT ON TABLE "HUNDISILM"."ALL_UT_LIB_VALIDATIONS"  IS 'Unit Test - Validation Code Hook Library';
