--------------------------------------------------------
--  DDL for View ALL_UT_VALIDATIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "HUNDISILM"."ALL_UT_VALIDATIONS" ("VALIDATION_ID", "UTI_ID", "INDEX_NO", "VALIDATION", "LIB_VALIDATION_ID", "CREATED_ON", "CREATED_BY", "APPLY_VALIDATION") AS 
  SELECT
    "VALIDATION_ID" AS "VALIDATION_ID"
   ,"UTI_ID" AS "UTI_ID"
   ,"INDEX_NO" AS "INDEX_NO"
   ,"VALIDATION" AS "VALIDATION"
   ,"LIB_VALIDATION_ID" AS "LIB_VALIDATION_ID"
   ,"CREATED_ON" AS "CREATED_ON"
   ,"CREATED_BY" AS "CREATED_BY"
   ,DECODE("APPLY_VALIDATION", 0, 'N', 'Y') AS "APPLY_VALIDATION"
  FROM
    "UT_VALIDATIONS"
  WITH READ ONLY;

   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_VALIDATIONS"."VALIDATION_ID" IS 'Validation Code Hook usage identifier';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_VALIDATIONS"."UTI_ID" IS 'Test Implementation identifier';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_VALIDATIONS"."INDEX_NO" IS 'Index within list of validations of Test Implementation';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_VALIDATIONS"."VALIDATION" IS 'Code Hook property XML';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_VALIDATIONS"."LIB_VALIDATION_ID" IS 'Library Validation Code Hook identifier when referencing library object';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_VALIDATIONS"."CREATED_ON" IS 'Creation timestamp';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_VALIDATIONS"."CREATED_BY" IS 'Created by user';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_VALIDATIONS"."APPLY_VALIDATION" IS 'Apply validation during test run - Y or N';
   COMMENT ON TABLE "HUNDISILM"."ALL_UT_VALIDATIONS"  IS 'Unit Test - Validation Code Hooks';
