--------------------------------------------------------
--  DDL for View ALL_UT_TEST_IMPL
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "HUNDISILM"."ALL_UT_TEST_IMPL" ("UTI_ID", "UT_ID", "NAME", "EXPECTED_RETURN", "EXPECTED_RETURN_ERROR", "DYNAMIC_VALUE_QUERY", "LIB_DYN_QUERY_ID", "CREATED_ON", "CREATED_BY") AS 
  SELECT
    "UTI_ID" AS "UTI_ID"
   ,"UT_ID" AS "UT_ID"
   ,"NAME" AS "NAME"
   ,"EXPECTED_RETURN" AS "EXPECTED_RETURN"
   ,"EXPECTED_RETURN_ERROR" AS "EXPECTED_RETURN_ERROR"
   ,"DYNAMIC_VALUE_QUERY" AS "DYNAMIC_VALUE_QUERY"
   ,"LIB_DYN_QUERY_ID" AS "LIB_DYN_QUERY_ID"
   ,"CREATED_ON" AS "CREATED_ON"
   ,"CREATED_BY" AS "CREATED_BY"
  FROM
    "UT_TEST_IMPL"
  WITH READ ONLY;

   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_TEST_IMPL"."UTI_ID" IS 'Test Implementation identifier';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_TEST_IMPL"."UT_ID" IS 'Test identifier';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_TEST_IMPL"."NAME" IS 'Implementation name';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_TEST_IMPL"."EXPECTED_RETURN" IS 'Expected returned status';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_TEST_IMPL"."EXPECTED_RETURN_ERROR" IS 'Expected returned error message ';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_TEST_IMPL"."DYNAMIC_VALUE_QUERY" IS 'Dynamic query used to populate test argument values';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_TEST_IMPL"."CREATED_ON" IS 'Creation timestamp';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_TEST_IMPL"."CREATED_BY" IS 'Created by user';
   COMMENT ON TABLE "HUNDISILM"."ALL_UT_TEST_IMPL"  IS 'Unit Test - Test Implementations';
