--------------------------------------------------------
--  DDL for View ALL_UT_TEST_IMPL_ARGUMENTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "HUNDISILM"."ALL_UT_TEST_IMPL_ARGUMENTS" ("UTI_ID", "ARG_ID", "INPUT_VALUE", "OUTPUT_VALUE", "TEST_OUTVAL") AS 
  SELECT
    "UTI_ID" AS "UTI_ID"
   ,"ARG_ID" AS "ARG_ID"
   ,"INPUT_VALUE" AS "INPUT_VALUE"
   ,"OUTPUT_VALUE" AS "OUTPUT_VALUE"
   ,DECODE("TEST_OUTVAL", 0, 'N', 'Y') AS "TEST_OUTVAL"
  FROM
    "UT_TEST_IMPL_ARGUMENTS"
  WITH READ ONLY;

   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_TEST_IMPL_ARGUMENTS"."UTI_ID" IS 'Test identifier';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_TEST_IMPL_ARGUMENTS"."ARG_ID" IS 'Test Argument identifier';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_TEST_IMPL_ARGUMENTS"."INPUT_VALUE" IS 'Input parameter value property XML';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_TEST_IMPL_ARGUMENTS"."OUTPUT_VALUE" IS 'Expected output parameter value property XML';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_TEST_IMPL_ARGUMENTS"."TEST_OUTVAL" IS 'Test output value - Y or N';
   COMMENT ON TABLE "HUNDISILM"."ALL_UT_TEST_IMPL_ARGUMENTS"  IS 'Unit Test - Test Implementation Arguments';
