--------------------------------------------------------
--  DDL for View ALL_UT_LIB_DYN_QUERIES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "HUNDISILM"."ALL_UT_LIB_DYN_QUERIES" ("LIB_DYN_QUERY_ID", "LIB_DYN_QUERY_NAME", "LIB_DYN_QUERY", "CREATED_ON", "CREATED_BY") AS 
  SELECT
    "LIB_DYN_QUERY_ID" AS "LIB_DYN_QUERY_ID"
   ,"LIB_DYN_QUERY_NAME" AS "LIB_DYN_QUERY_NAME"
   ,"LIB_DYN_QUERY" AS "LIB_DYN_QUERY"
   ,"CREATED_ON" AS "CREATED_ON"
   ,"CREATED_BY" AS "CREATED_BY"
  FROM
    "UT_LIB_DYN_QUERIES"
  WITH READ ONLY;

   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_DYN_QUERIES"."LIB_DYN_QUERY_ID" IS 'Library Dynamic Value Query Code Hook identifier';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_DYN_QUERIES"."LIB_DYN_QUERY_NAME" IS 'Code Hook name';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_DYN_QUERIES"."LIB_DYN_QUERY" IS 'Code Hook property XML';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_DYN_QUERIES"."CREATED_ON" IS 'Creation timestamp';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_DYN_QUERIES"."CREATED_BY" IS 'Created by user';
   COMMENT ON TABLE "HUNDISILM"."ALL_UT_LIB_DYN_QUERIES"  IS 'Unit Test - Dynamic Value Query Code Hook Library';
