--------------------------------------------------------
--  DDL for View ALL_UT_LIB_TEARDOWNS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "HUNDISILM"."ALL_UT_LIB_TEARDOWNS" ("LIB_TEARDOWN_ID", "LIB_TEARDOWN_NAME", "LIB_TEARDOWN_CLASS", "LIB_TEARDOWN", "CREATED_ON", "CREATED_BY") AS 
  SELECT
    "LIB_TEARDOWN_ID" AS "LIB_TEARDOWN_ID"
   ,"LIB_TEARDOWN_NAME" AS "LIB_TEARDOWN_NAME"
   ,"LIB_TEARDOWN_CLASS" AS "LIB_TEARDOWN_CLASS"
   ,"LIB_TEARDOWN" AS "LIB_TEARDOWN"
   ,"CREATED_ON" AS "CREATED_ON"
   ,"CREATED_BY" AS "CREATED_BY"
  FROM
    "UT_LIB_TEARDOWNS"
  WITH READ ONLY;

   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_TEARDOWNS"."LIB_TEARDOWN_ID" IS 'Library Teardown Code Hook identifier';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_TEARDOWNS"."LIB_TEARDOWN_NAME" IS 'Code Hook name';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_TEARDOWNS"."LIB_TEARDOWN_CLASS" IS 'Implementing Java class name';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_TEARDOWNS"."LIB_TEARDOWN" IS 'Code Hook property XML';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_TEARDOWNS"."CREATED_ON" IS 'Creation timestamp';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_TEARDOWNS"."CREATED_BY" IS 'Created by user';
   COMMENT ON TABLE "HUNDISILM"."ALL_UT_LIB_TEARDOWNS"  IS 'Unit Test - Teardown Code Hook Library';
