--------------------------------------------------------
--  DDL for View ALL_UT_LIB_STARTUPS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "HUNDISILM"."ALL_UT_LIB_STARTUPS" ("LIB_STARTUP_ID", "LIB_STARTUP_NAME", "LIB_STARTUP_CLASS", "LIB_STARTUP", "CREATED_ON", "CREATED_BY") AS 
  SELECT
    "LIB_STARTUP_ID" AS "LIB_STARTUP_ID"
   ,"LIB_STARTUP_NAME" AS "LIB_STARTUP_NAME"
   ,"LIB_STARTUP_CLASS" AS "LIB_STARTUP_CLASS"
   ,"LIB_STARTUP" AS "LIB_STARTUP"
   ,"CREATED_ON" AS "CREATED_ON"
   ,"CREATED_BY" AS "CREATED_BY"
  FROM
    "UT_LIB_STARTUPS"
  WITH READ ONLY;

   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_STARTUPS"."LIB_STARTUP_ID" IS 'Library Startup Code Hook identifier';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_STARTUPS"."LIB_STARTUP_NAME" IS 'Code Hook name';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_STARTUPS"."LIB_STARTUP_CLASS" IS 'Implementing Java class name';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_STARTUPS"."LIB_STARTUP" IS 'Code Hook property XML';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_STARTUPS"."CREATED_ON" IS 'Creation timestamp';
   COMMENT ON COLUMN "HUNDISILM"."ALL_UT_LIB_STARTUPS"."CREATED_BY" IS 'Created by user';
   COMMENT ON TABLE "HUNDISILM"."ALL_UT_LIB_STARTUPS"  IS 'Unit Test - Startup Code Hook Library';
