--------------------------------------------------------
--  Constraints for Table B_APPLICATIONS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."B_APPLICATIONS" ADD CONSTRAINT "B_APPLICANTS_PK" PRIMARY KEY ("APL_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HUNDISILM"."B_APPLICATIONS" ADD CONSTRAINT "B_APPLICATION_DATA_CHK1" CHECK (APL_REJECTED IN (0,1)) ENABLE;
  ALTER TABLE "HUNDISILM"."B_APPLICATIONS" MODIFY ("APL_CODE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_APPLICATIONS" MODIFY ("APL_REJECTED" NOT NULL ENABLE);
