--------------------------------------------------------
--  DDL for Table B_APP_CHECKS
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."B_APP_CHECKS" 
   (	"ACK_CODE" NUMBER(*,0), 
	"ACK_APL_CODE" NUMBER(*,0), 
	"ACK_CHK_CODE" NUMBER(*,0), 
	"ACK_VALUE" NUMBER(*,0), 
	"ACK_SRN_CODE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HUNDISILM"."B_APP_CHECKS"."ACK_CODE" IS 'Primary key';
   COMMENT ON COLUMN "HUNDISILM"."B_APP_CHECKS"."ACK_APL_CODE" IS 'Application code';
   COMMENT ON COLUMN "HUNDISILM"."B_APP_CHECKS"."ACK_CHK_CODE" IS 'Check code';
   COMMENT ON COLUMN "HUNDISILM"."B_APP_CHECKS"."ACK_VALUE" IS 'Check value: -1 not defined, 0 - false, 1 - true';
   COMMENT ON COLUMN "HUNDISILM"."B_APP_CHECKS"."ACK_SRN_CODE" IS 'Reference to the run ID
';
