--------------------------------------------------------
--  Constraints for Table B_APP_CONTROLLERS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."B_APP_CONTROLLERS" MODIFY ("ACO_CONTROLLER" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_APP_CONTROLLERS" MODIFY ("ACO_TABLE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_APP_CONTROLLERS" MODIFY ("ACO_CODE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_APP_CONTROLLERS" ADD CONSTRAINT "B_APP_CONTROLLERS_PK" PRIMARY KEY ("ACO_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HUNDISILM"."B_APP_CONTROLLERS" ADD CONSTRAINT "B_APP_CONTROLLERS_UK1" UNIQUE ("ACO_CONTROLLER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
