--------------------------------------------------------
--  DDL for Table B_APP_CONTROLLERS
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."B_APP_CONTROLLERS" 
   (	"ACO_CODE" NUMBER(*,0), 
	"ACO_CONTROLLER" VARCHAR2(200 BYTE), 
	"ACO_TABLE" VARCHAR2(200 BYTE), 
	"ACO_VIEW_TYPE" VARCHAR2(200 BYTE), 
	"ACO_PARENT_TABLE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HUNDISILM"."B_APP_CONTROLLERS"."ACO_CONTROLLER" IS 'Controller name';
   COMMENT ON COLUMN "HUNDISILM"."B_APP_CONTROLLERS"."ACO_TABLE" IS 'Main table for the controller';
   COMMENT ON COLUMN "HUNDISILM"."B_APP_CONTROLLERS"."ACO_VIEW_TYPE" IS 'View Type for (i.e. table, grid)';
   COMMENT ON COLUMN "HUNDISILM"."B_APP_CONTROLLERS"."ACO_PARENT_TABLE" IS 'Parent Table';
