--------------------------------------------------------
--  DDL for Table B_APPLICATIONS
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."B_APPLICATIONS" 
   (	"APL_CODE" NUMBER(*,0), 
	"APL_NAME" VARCHAR2(200 BYTE), 
	"APL_INCOME" NUMBER, 
	"APL_OBLIGATIONS" NUMBER, 
	"APL_RESERVE" NUMBER, 
	"APL_DEBT_TO_INCOME" NUMBER, 
	"APL_AGE" NUMBER, 
	"APL_EDUCATION" VARCHAR2(100 BYTE), 
	"APL_REJECTED" NUMBER(*,0), 
	"APL_IN_DEFAULT" NUMBER(*,0), 
	"APL_AMOUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HUNDISILM"."B_APPLICATIONS"."APL_CODE" IS 'Primary key';
   COMMENT ON COLUMN "HUNDISILM"."B_APPLICATIONS"."APL_NAME" IS 'Name of the applicant.';
   COMMENT ON COLUMN "HUNDISILM"."B_APPLICATIONS"."APL_INCOME" IS 'Applicant income';
   COMMENT ON COLUMN "HUNDISILM"."B_APPLICATIONS"."APL_OBLIGATIONS" IS 'Applicant obligations';
   COMMENT ON COLUMN "HUNDISILM"."B_APPLICATIONS"."APL_RESERVE" IS 'Applicant reserve';
   COMMENT ON COLUMN "HUNDISILM"."B_APPLICATIONS"."APL_DEBT_TO_INCOME" IS 'Applicant debt to income ratio';
   COMMENT ON COLUMN "HUNDISILM"."B_APPLICATIONS"."APL_AGE" IS 'Applicant Age in full years';
   COMMENT ON COLUMN "HUNDISILM"."B_APPLICATIONS"."APL_EDUCATION" IS 'Applicant education level';
   COMMENT ON COLUMN "HUNDISILM"."B_APPLICATIONS"."APL_REJECTED" IS 'Whether applicatio was rejected or not';
   COMMENT ON COLUMN "HUNDISILM"."B_APPLICATIONS"."APL_IN_DEFAULT" IS 'Whether applicants contracts are in defult';
   COMMENT ON COLUMN "HUNDISILM"."B_APPLICATIONS"."APL_AMOUNT" IS 'Applied loan amount';
