--------------------------------------------------------
--  DDL for Table B_CHECK_SUITS
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."B_CHECK_SUITS" 
   (	"CHS_CODE" NUMBER(38,0), 
	"CHS_MNEMO" VARCHAR2(100 BYTE), 
	"CHS_COMMENT" VARCHAR2(2000 BYTE), 
	"CHS_DATETIME" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HUNDISILM"."B_CHECK_SUITS"."CHS_CODE" IS 'Primary key';
   COMMENT ON COLUMN "HUNDISILM"."B_CHECK_SUITS"."CHS_MNEMO" IS 'Mnemo for the check suite';
   COMMENT ON COLUMN "HUNDISILM"."B_CHECK_SUITS"."CHS_COMMENT" IS 'Comment for the suite';
   COMMENT ON COLUMN "HUNDISILM"."B_CHECK_SUITS"."CHS_DATETIME" IS 'Time of the suite creation';
