--------------------------------------------------------
--  DDL for Table B_CHECK_LOVS
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."B_CHECK_LOVS" 
   (	"CLV_CODE" NUMBER(*,0), 
	"CLV_VALUE" VARCHAR2(2000 BYTE), 
	"CLV_LCP_CODE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HUNDISILM"."B_CHECK_LOVS"."CLV_CODE" IS 'Primary key for lov option';
   COMMENT ON COLUMN "HUNDISILM"."B_CHECK_LOVS"."CLV_VALUE" IS 'String value of the lov';
   COMMENT ON COLUMN "HUNDISILM"."B_CHECK_LOVS"."CLV_LCP_CODE" IS 'LOV_PARS to which the lov value belongs to';
