--------------------------------------------------------
--  Constraints for Table B_CHECK_LOVS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."B_CHECK_LOVS" MODIFY ("CLV_CODE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_CHECK_LOVS" ADD CONSTRAINT "B_CHECK_LOVS_PK" PRIMARY KEY ("CLV_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HUNDISILM"."B_CHECK_LOVS" MODIFY ("CLV_LCP_CODE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_CHECK_LOVS" MODIFY ("CLV_VALUE" NOT NULL ENABLE);
