--------------------------------------------------------
--  DDL for Table B_CHECKS
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."B_CHECKS" 
   (	"CHK_CODE" NUMBER(*,0), 
	"CHK_MNEMO" VARCHAR2(50 BYTE), 
	"CHK_TYPE" VARCHAR2(20 BYTE), 
	"CHK_COMMENT" VARCHAR2(2000 BYTE), 
	"CHK_ACTIVE" NUMBER(*,0), 
	"CHK_CHS_CODE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HUNDISILM"."B_CHECKS"."CHK_CODE" IS 'Primary key';
   COMMENT ON COLUMN "HUNDISILM"."B_CHECKS"."CHK_MNEMO" IS 'Check mnemo';
   COMMENT ON COLUMN "HUNDISILM"."B_CHECKS"."CHK_TYPE" IS 'chk type: min, max,lov,excl_lov,func';
   COMMENT ON COLUMN "HUNDISILM"."B_CHECKS"."CHK_COMMENT" IS 'Comment for the Check.';
   COMMENT ON COLUMN "HUNDISILM"."B_CHECKS"."CHK_ACTIVE" IS 'Whether Check is currently active or not (0 = inactive 1 = active)';
   COMMENT ON COLUMN "HUNDISILM"."B_CHECKS"."CHK_CHS_CODE" IS 'Suit Code';
