--------------------------------------------------------
--  Constraints for Table B_CONTROLLER_SIBLINGS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."B_CONTROLLER_SIBLINGS" MODIFY ("COS_CODE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_CONTROLLER_SIBLINGS" ADD CONSTRAINT "B_CONTROLLER_SIBLINGS_PK" PRIMARY KEY ("COS_CODE")
  USING INDEX (CREATE UNIQUE INDEX "HUNDISILM"."B_APP_CHILDREN_PK" ON "HUNDISILM"."B_CONTROLLER_SIBLINGS" ("COS_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HUNDISILM"."B_CONTROLLER_SIBLINGS" ADD CONSTRAINT "B_CONTROLLER_SIBLINGS_CHK1" CHECK (COS_TYPE = 'PARENT' OR COS_TYPE='CHILD') ENABLE;
