--------------------------------------------------------
--  DDL for Table B_LOV_CHECK_PARS
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."B_LOV_CHECK_PARS" 
   (	"LCP_CODE" NUMBER(*,0), 
	"LCP_CHK_CODE" NUMBER(*,0), 
	"LCP_CHECK_FIELD" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HUNDISILM"."B_LOV_CHECK_PARS"."LCP_CODE" IS 'Primary Key';
   COMMENT ON COLUMN "HUNDISILM"."B_LOV_CHECK_PARS"."LCP_CHK_CODE" IS 'Check to which the LOV belongs to.';
   COMMENT ON COLUMN "HUNDISILM"."B_LOV_CHECK_PARS"."LCP_CHECK_FIELD" IS 'Application Field name which to check.';
