--------------------------------------------------------
--  Constraints for Table B_LOV_CHECK_PARS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."B_LOV_CHECK_PARS" MODIFY ("LCP_CODE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_LOV_CHECK_PARS" MODIFY ("LCP_CHK_CODE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_LOV_CHECK_PARS" ADD CONSTRAINT "B_LOV_CHECK_PARS_PK" PRIMARY KEY ("LCP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
