--------------------------------------------------------
--  DDL for Table B_MINMAX_CHECK_PARS
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."B_MINMAX_CHECK_PARS" 
   (	"MCP_CODE" NUMBER(*,0), 
	"MCP_CHK_CODE" NUMBER(*,0), 
	"MCP_THRESHOLD" NUMBER, 
	"MCP_CHECK_FIELD" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HUNDISILM"."B_MINMAX_CHECK_PARS"."MCP_CODE" IS 'Primary Key';
   COMMENT ON COLUMN "HUNDISILM"."B_MINMAX_CHECK_PARS"."MCP_CHK_CODE" IS 'Reference to the check the pars apply to.';
   COMMENT ON COLUMN "HUNDISILM"."B_MINMAX_CHECK_PARS"."MCP_THRESHOLD" IS 'Threshold value to check against.';
   COMMENT ON COLUMN "HUNDISILM"."B_MINMAX_CHECK_PARS"."MCP_CHECK_FIELD" IS 'Field which value to check.';
