--------------------------------------------------------
--  DDL for Table B_MINMAX_ITERATORS
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."B_MINMAX_ITERATORS" 
   (	"MMI_CODE" NUMBER(*,0), 
	"MMI_MNEMO" VARCHAR2(200 BYTE), 
	"MMI_FIELD" VARCHAR2(200 BYTE), 
	"MMI_THRESHOLD_FROM" NUMBER, 
	"MMI_THRESHOLD_TO" NUMBER, 
	"MMI_STEP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HUNDISILM"."B_MINMAX_ITERATORS"."MMI_CODE" IS 'Primary Key';
   COMMENT ON COLUMN "HUNDISILM"."B_MINMAX_ITERATORS"."MMI_MNEMO" IS 'Iterator mnemo';
   COMMENT ON COLUMN "HUNDISILM"."B_MINMAX_ITERATORS"."MMI_FIELD" IS 'Field over which to iterate.';
   COMMENT ON COLUMN "HUNDISILM"."B_MINMAX_ITERATORS"."MMI_THRESHOLD_FROM" IS 'Iterations start value.';
   COMMENT ON COLUMN "HUNDISILM"."B_MINMAX_ITERATORS"."MMI_THRESHOLD_TO" IS 'Iterations end value.';
   COMMENT ON COLUMN "HUNDISILM"."B_MINMAX_ITERATORS"."MMI_STEP" IS 'Iteration increment';
