--------------------------------------------------------
--  Constraints for Table B_PRETTY_NAMES
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."B_PRETTY_NAMES" MODIFY ("PRN_CODE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_PRETTY_NAMES" MODIFY ("PRN_TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_PRETTY_NAMES" MODIFY ("PRN_COLUMN_NAME" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_PRETTY_NAMES" MODIFY ("PRN_PRETTY_NAME" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_PRETTY_NAMES" ADD CONSTRAINT "B_PRETTY_NAMES_PK" PRIMARY KEY ("PRN_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HUNDISILM"."B_PRETTY_NAMES" ADD CONSTRAINT "B_PRETTY_NAMES_UK1" UNIQUE ("PRN_TABLE_NAME", "PRN_COLUMN_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
