--------------------------------------------------------
--  DDL for Table B_PRETTY_NAMES
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."B_PRETTY_NAMES" 
   (	"PRN_CODE" NUMBER(*,0), 
	"PRN_TABLE_NAME" VARCHAR2(200 BYTE), 
	"PRN_COLUMN_NAME" VARCHAR2(200 BYTE), 
	"PRN_PRETTY_NAME" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HUNDISILM"."B_PRETTY_NAMES"."PRN_CODE" IS 'Primary Key';
   COMMENT ON COLUMN "HUNDISILM"."B_PRETTY_NAMES"."PRN_TABLE_NAME" IS 'Table or View name which holds the column';
   COMMENT ON COLUMN "HUNDISILM"."B_PRETTY_NAMES"."PRN_COLUMN_NAME" IS 'Column Name for which the pretty name is applied';
   COMMENT ON COLUMN "HUNDISILM"."B_PRETTY_NAMES"."PRN_PRETTY_NAME" IS 'Pretty Name for the column';
