--------------------------------------------------------
--  Constraints for Table B_RPREDICT_CHECK_PARS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."B_RPREDICT_CHECK_PARS" ADD CONSTRAINT "B_RPREDICT_CHECK_PARS_UK1" UNIQUE ("RCP_CHK_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HUNDISILM"."B_RPREDICT_CHECK_PARS" MODIFY ("RCP_CODE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_RPREDICT_CHECK_PARS" MODIFY ("RCP_CHK_CODE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_RPREDICT_CHECK_PARS" ADD CONSTRAINT "B_RPREDICT_CHECK_PARS_PK" PRIMARY KEY ("RCP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HUNDISILM"."B_RPREDICT_CHECK_PARS" MODIFY ("RCP_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_RPREDICT_CHECK_PARS" MODIFY ("RCP_THRESHOLD" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_RPREDICT_CHECK_PARS" MODIFY ("RCP_MODEL" NOT NULL ENABLE);
