--------------------------------------------------------
--  DDL for Table B_RPREDICT_CHECK_PARS
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."B_RPREDICT_CHECK_PARS" 
   (	"RCP_CODE" NUMBER(*,0), 
	"RCP_TYPE" VARCHAR2(20 BYTE), 
	"RCP_THRESHOLD" NUMBER, 
	"RCP_CHK_CODE" NUMBER(*,0), 
	"RCP_MODEL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HUNDISILM"."B_RPREDICT_CHECK_PARS"."RCP_CODE" IS 'Primary Key';
   COMMENT ON COLUMN "HUNDISILM"."B_RPREDICT_CHECK_PARS"."RCP_TYPE" IS 'Threshold value mode (minimum or maximum)';
   COMMENT ON COLUMN "HUNDISILM"."B_RPREDICT_CHECK_PARS"."RCP_THRESHOLD" IS 'Threshold value ';
   COMMENT ON COLUMN "HUNDISILM"."B_RPREDICT_CHECK_PARS"."RCP_CHK_CODE" IS 'Check to which parameters belong to.';
   COMMENT ON COLUMN "HUNDISILM"."B_RPREDICT_CHECK_PARS"."RCP_MODEL" IS 'DataStore name where the model is held.';
