--------------------------------------------------------
--  DDL for Table B_RUN_STATS
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."B_RUN_STATS" 
   (	"RST_CODE" NUMBER(*,0), 
	"RST_SRN_CODE" NUMBER(*,0), 
	"RST_TOTAL_APPLS" NUMBER(*,0), 
	"RST_TOTAL_AMOUNT" NUMBER, 
	"RST_ACCEPTED_APPLS" NUMBER(*,0), 
	"RST_ACCEPTED_AMOUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HUNDISILM"."B_RUN_STATS"."RST_CODE" IS 'Primary key';
   COMMENT ON COLUMN "HUNDISILM"."B_RUN_STATS"."RST_SRN_CODE" IS 'Reference to the run which stats are stored';
   COMMENT ON COLUMN "HUNDISILM"."B_RUN_STATS"."RST_TOTAL_APPLS" IS 'Total number of applications in the dataset';
   COMMENT ON COLUMN "HUNDISILM"."B_RUN_STATS"."RST_TOTAL_AMOUNT" IS 'Total applied amount';
   COMMENT ON COLUMN "HUNDISILM"."B_RUN_STATS"."RST_ACCEPTED_APPLS" IS 'Total accepted applications';
   COMMENT ON COLUMN "HUNDISILM"."B_RUN_STATS"."RST_ACCEPTED_AMOUNT" IS 'Total amount accepted';
