--------------------------------------------------------
--  DDL for Table B_SCENARIO_CHECKS
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."B_SCENARIO_CHECKS" 
   (	"SCC_CODE" NUMBER(*,0), 
	"SCC_APL_CODE" NUMBER(*,0), 
	"SCC_VALUE" NUMBER(*,0), 
	"SCC_SRN_CODE" NUMBER(*,0), 
	"SCC_CHK_CODE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HUNDISILM"."B_SCENARIO_CHECKS"."SCC_CODE" IS 'Primary key';
   COMMENT ON COLUMN "HUNDISILM"."B_SCENARIO_CHECKS"."SCC_APL_CODE" IS 'Application code to which the check belongs to.';
   COMMENT ON COLUMN "HUNDISILM"."B_SCENARIO_CHECKS"."SCC_VALUE" IS 'Result of the check.';
   COMMENT ON COLUMN "HUNDISILM"."B_SCENARIO_CHECKS"."SCC_SRN_CODE" IS 'Run code of the check.';
   COMMENT ON COLUMN "HUNDISILM"."B_SCENARIO_CHECKS"."SCC_CHK_CODE" IS 'Check which was run';
