--------------------------------------------------------
--  DDL for Table B_SCENARIO_RUNS
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."B_SCENARIO_RUNS" 
   (	"SCR_CODE" NUMBER(*,0), 
	"SCR_SSC_CODE" NUMBER(*,0), 
	"SCR_SRN_CODE" NUMBER(*,0), 
	"SCR_TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HUNDISILM"."B_SCENARIO_RUNS"."SCR_CODE" IS 'Primary key';
   COMMENT ON COLUMN "HUNDISILM"."B_SCENARIO_RUNS"."SCR_SSC_CODE" IS 'Scenario code';
   COMMENT ON COLUMN "HUNDISILM"."B_SCENARIO_RUNS"."SCR_SRN_CODE" IS 'Run Code';
   COMMENT ON COLUMN "HUNDISILM"."B_SCENARIO_RUNS"."SCR_TYPE" IS 'Either ''BASE'' or ''ITERATION''';
   COMMENT ON TABLE "HUNDISILM"."B_SCENARIO_RUNS"  IS 'Table stores the link between scenarios and runs.';
