--------------------------------------------------------
--  Constraints for Table B_SCENARIO_CHECKS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."B_SCENARIO_CHECKS" MODIFY ("SCC_CODE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_SCENARIO_CHECKS" ADD CONSTRAINT "B_SCENARIO_CHECKS_PK" PRIMARY KEY ("SCC_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HUNDISILM"."B_SCENARIO_CHECKS" MODIFY ("SCC_APL_CODE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_SCENARIO_CHECKS" MODIFY ("SCC_VALUE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_SCENARIO_CHECKS" MODIFY ("SCC_SRN_CODE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_SCENARIO_CHECKS" MODIFY ("SCC_CHK_CODE" NOT NULL ENABLE);
