--------------------------------------------------------
--  Ref Constraints for Table B_SCENARIO_RUNS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."B_SCENARIO_RUNS" ADD CONSTRAINT "B_SCENARIO_RUNS_FK1" FOREIGN KEY ("SCR_SSC_CODE")
	  REFERENCES "HUNDISILM"."B_SUITE_SCENARIOS" ("SSC_CODE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "HUNDISILM"."B_SCENARIO_RUNS" ADD CONSTRAINT "B_SCENARIO_RUNS_FK2" FOREIGN KEY ("SCR_SRN_CODE")
	  REFERENCES "HUNDISILM"."B_SUITE_RUNS" ("SRN_CODE") ON DELETE CASCADE ENABLE;
