--------------------------------------------------------
--  DDL for Table B_SCENARIO_CHECK_PARS
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."B_SCENARIO_CHECK_PARS" 
   (	"SCP_CODE" NUMBER(*,0), 
	"SCP_CHK_MNEMO" VARCHAR2(200 BYTE), 
	"SCP_CHK_TYPE" VARCHAR2(200 BYTE), 
	"SCP_PAR_NAME" VARCHAR2(200 BYTE), 
	"SCP_PAR_VALUE" VARCHAR2(2000 BYTE), 
	"SCP_SRN_CODE" NUMBER(*,0), 
	"SCP_SSC_CODE" NUMBER(*,0), 
	"SCP_TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HUNDISILM"."B_SCENARIO_CHECK_PARS"."SCP_CODE" IS 'Primary key';
   COMMENT ON COLUMN "HUNDISILM"."B_SCENARIO_CHECK_PARS"."SCP_CHK_MNEMO" IS 'Reference to the check';
   COMMENT ON COLUMN "HUNDISILM"."B_SCENARIO_CHECK_PARS"."SCP_CHK_TYPE" IS 'Type of the related check';
   COMMENT ON COLUMN "HUNDISILM"."B_SCENARIO_CHECK_PARS"."SCP_PAR_NAME" IS 'Name of the parameter';
   COMMENT ON COLUMN "HUNDISILM"."B_SCENARIO_CHECK_PARS"."SCP_PAR_VALUE" IS 'Value of the parameter';
   COMMENT ON COLUMN "HUNDISILM"."B_SCENARIO_CHECK_PARS"."SCP_SRN_CODE" IS 'Reference to the run to which it belongs to';
   COMMENT ON COLUMN "HUNDISILM"."B_SCENARIO_CHECK_PARS"."SCP_SSC_CODE" IS 'Reference to the scenario';
   COMMENT ON COLUMN "HUNDISILM"."B_SCENARIO_CHECK_PARS"."SCP_TYPE" IS 'Either "BASE" or "ITERATION"';
