--------------------------------------------------------
--  Ref Constraints for Table B_SCENARIO_CHECK_PARS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."B_SCENARIO_CHECK_PARS" ADD CONSTRAINT "B_SCENARIO_CHECK_PARS_FK2" FOREIGN KEY ("SCP_SRN_CODE")
	  REFERENCES "HUNDISILM"."B_SUITE_RUNS" ("SRN_CODE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "HUNDISILM"."B_SCENARIO_CHECK_PARS" ADD CONSTRAINT "B_SCENARIO_CHECK_PARS_FK3" FOREIGN KEY ("SCP_SSC_CODE")
	  REFERENCES "HUNDISILM"."B_SUITE_SCENARIOS" ("SSC_CODE") ON DELETE CASCADE ENABLE;
