--------------------------------------------------------
--  DDL for Table B_SUITE_SCENARIOS
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."B_SUITE_SCENARIOS" 
   (	"SSC_CODE" NUMBER(*,0), 
	"SSC_CHS_CODE" NUMBER(*,0), 
	"SSC_MNEMO" VARCHAR2(200 BYTE), 
	"SSC_COMMENT" VARCHAR2(2000 BYTE), 
	"SSC_CHK_MNEMO" VARCHAR2(200 BYTE), 
	"SSC_ITERATOR_CODE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HUNDISILM"."B_SUITE_SCENARIOS"."SSC_CODE" IS 'Primary key';
   COMMENT ON COLUMN "HUNDISILM"."B_SUITE_SCENARIOS"."SSC_CHS_CODE" IS 'Suite code to which this scenario belongs to.';
   COMMENT ON COLUMN "HUNDISILM"."B_SUITE_SCENARIOS"."SSC_MNEMO" IS 'Scenario Mnemo';
   COMMENT ON COLUMN "HUNDISILM"."B_SUITE_SCENARIOS"."SSC_COMMENT" IS 'Short scenario descrition';
   COMMENT ON COLUMN "HUNDISILM"."B_SUITE_SCENARIOS"."SSC_CHK_MNEMO" IS 'Reference to the check over which to iterate.';
   COMMENT ON COLUMN "HUNDISILM"."B_SUITE_SCENARIOS"."SSC_ITERATOR_CODE" IS 'Reference to iterator which to use.';
