--------------------------------------------------------
--  Constraints for Table B_SUITE_SCENARIOS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."B_SUITE_SCENARIOS" MODIFY ("SSC_CODE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_SUITE_SCENARIOS" MODIFY ("SSC_CHS_CODE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_SUITE_SCENARIOS" MODIFY ("SSC_MNEMO" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_SUITE_SCENARIOS" ADD CONSTRAINT "B_SUITE_SCENARIOS_PK" PRIMARY KEY ("SSC_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
