--------------------------------------------------------
--  Constraints for Table B_TABLE_COL_LOV_PARS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."B_TABLE_COL_LOV_PARS" MODIFY ("TLP_CODE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_TABLE_COL_LOV_PARS" MODIFY ("TLP_TABLE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_TABLE_COL_LOV_PARS" MODIFY ("TLP_COLUMN" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_TABLE_COL_LOV_PARS" MODIFY ("TLP_SELECT_SQL" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."B_TABLE_COL_LOV_PARS" ADD CONSTRAINT "B_TABLE_COL_LOV_PARS_PK" PRIMARY KEY ("TLP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
