--------------------------------------------------------
--  DDL for Table ERR$_B_SCENARIO_CHECKS
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."ERR$_B_SCENARIO_CHECKS" 
   (	"ORA_ERR_NUMBER$" NUMBER, 
	"ORA_ERR_MESG$" VARCHAR2(2000 BYTE), 
	"ORA_ERR_ROWID$" UROWID (4000), 
	"ORA_ERR_OPTYP$" VARCHAR2(2 BYTE), 
	"ORA_ERR_TAG$" VARCHAR2(2000 BYTE), 
	"SCC_CODE" VARCHAR2(4000 BYTE), 
	"SCC_APL_CODE" VARCHAR2(4000 BYTE), 
	"SCC_VALUE" VARCHAR2(4000 BYTE), 
	"SCC_SRN_CODE" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "HUNDISILM"."ERR$_B_SCENARIO_CHECKS"  IS 'DML Error Logging table for "B_SCENARIO_CHECKS"';
