--------------------------------------------------------
--  DDL for Trigger TABLE_CLOV_PARS#COLUMN#UPPER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "HUNDISILM"."TABLE_CLOV_PARS#COLUMN#UPPER" 
BEFORE INSERT OR UPDATE OF TLP_COLUMN ON B_TABLE_COL_LOV_PARS
FOR EACH ROW
BEGIN
  :NEW.TLP_COLUMN := UPPER(:NEW.TLP_COLUMN);
END;
/
ALTER TRIGGER "HUNDISILM"."TABLE_CLOV_PARS#COLUMN#UPPER" ENABLE;
