--------------------------------------------------------
--  DDL for Table UT_LIB_STARTUPS
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."UT_LIB_STARTUPS" 
   (	"LIB_STARTUP_ID" VARCHAR2(40 BYTE), 
	"LIB_STARTUP_NAME" VARCHAR2(120 BYTE), 
	"LIB_STARTUP_CLASS" VARCHAR2(120 BYTE), 
	"LIB_STARTUP" CLOB, 
	"CREATED_ON" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(120 BYTE), 
	"UPDATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("LIB_STARTUP") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
