--------------------------------------------------------
--  Constraints for Table UT_LIB_DYN_QUERIES
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."UT_LIB_DYN_QUERIES" MODIFY ("LIB_DYN_QUERY_ID" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_LIB_DYN_QUERIES" MODIFY ("LIB_DYN_QUERY_NAME" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_LIB_DYN_QUERIES" MODIFY ("LIB_DYN_QUERY_CLASS" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_LIB_DYN_QUERIES" MODIFY ("LIB_DYN_QUERY" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_LIB_DYN_QUERIES" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_LIB_DYN_QUERIES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_LIB_DYN_QUERIES" MODIFY ("UPDATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_LIB_DYN_QUERIES" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_LIB_DYN_QUERIES" ADD CONSTRAINT "UT_LIB_DYN_QUERIES_PK" PRIMARY KEY ("LIB_DYN_QUERY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HUNDISILM"."UT_LIB_DYN_QUERIES" ADD CONSTRAINT "UT_LIB_DYN_QUERIES_NAME" UNIQUE ("LIB_DYN_QUERY_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
