--------------------------------------------------------
--  DDL for Table UT_LIB_DYN_QUERIES
--------------------------------------------------------

  CREATE TABLE "HUNDISILM"."UT_LIB_DYN_QUERIES" 
   (	"LIB_DYN_QUERY_ID" VARCHAR2(40 BYTE), 
	"LIB_DYN_QUERY_NAME" VARCHAR2(120 BYTE), 
	"LIB_DYN_QUERY_CLASS" VARCHAR2(120 BYTE), 
	"LIB_DYN_QUERY" CLOB, 
	"CREATED_ON" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(120 BYTE), 
	"UPDATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("LIB_DYN_QUERY") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
