--------------------------------------------------------
--  Constraints for Table UT_LIB_TEARDOWNS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."UT_LIB_TEARDOWNS" MODIFY ("LIB_TEARDOWN_ID" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_LIB_TEARDOWNS" MODIFY ("LIB_TEARDOWN_NAME" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_LIB_TEARDOWNS" MODIFY ("LIB_TEARDOWN_CLASS" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_LIB_TEARDOWNS" MODIFY ("LIB_TEARDOWN" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_LIB_TEARDOWNS" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_LIB_TEARDOWNS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_LIB_TEARDOWNS" MODIFY ("UPDATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_LIB_TEARDOWNS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_LIB_TEARDOWNS" ADD CONSTRAINT "UT_LIB_TEARDOWNS_PK" PRIMARY KEY ("LIB_TEARDOWN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HUNDISILM"."UT_LIB_TEARDOWNS" ADD CONSTRAINT "UT_LIB_TEARDOWNS_NAME" UNIQUE ("LIB_TEARDOWN_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
