--------------------------------------------------------
--  Ref Constraints for Table UT_SUITE_ITEMS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."UT_SUITE_ITEMS" ADD CONSTRAINT "UT_SUITE_ITEMS_FK1" FOREIGN KEY ("UT_SID")
	  REFERENCES "HUNDISILM"."UT_SUITE" ("UT_SID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "HUNDISILM"."UT_SUITE_ITEMS" ADD CONSTRAINT "UT_SUITE_ITEMS_FK2" FOREIGN KEY ("UT_ID")
	  REFERENCES "HUNDISILM"."UT_TEST" ("UT_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "HUNDISILM"."UT_SUITE_ITEMS" ADD CONSTRAINT "UT_SUITE_ITEMS_FK3" FOREIGN KEY ("UT_NSID")
	  REFERENCES "HUNDISILM"."UT_SUITE" ("UT_SID") ON DELETE CASCADE ENABLE;
