--------------------------------------------------------
--  Constraints for Table UT_STARTUPS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."UT_STARTUPS" MODIFY ("STARTUP_ID" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_STARTUPS" MODIFY ("INDEX_NO" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_STARTUPS" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_STARTUPS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_STARTUPS" MODIFY ("UPDATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_STARTUPS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_STARTUPS" ADD CONSTRAINT "UT_STARTUPS_CHECK" CHECK ("STARTUP" IS NULL  OR "LIB_STARTUP_ID" IS NULL) ENABLE;
  ALTER TABLE "HUNDISILM"."UT_STARTUPS" ADD CONSTRAINT "UT_STARTUPS_PK" PRIMARY KEY ("STARTUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
