--------------------------------------------------------
--  Constraints for Table UT_SUITE
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."UT_SUITE" MODIFY ("UT_SID" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_SUITE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_SUITE" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_SUITE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_SUITE" MODIFY ("UPDATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_SUITE" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_SUITE" ADD CONSTRAINT "UT_SUITE_PK" PRIMARY KEY ("UT_SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
