--------------------------------------------------------
--  Constraints for Table UT_SUITE_ITEMS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."UT_SUITE_ITEMS" MODIFY ("UPDATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_SUITE_ITEMS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_SUITE_ITEMS" ADD CONSTRAINT "UT_SUITE_ITEMS_UK" UNIQUE ("UT_SID", "UT_ID", "UT_NSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HUNDISILM"."UT_SUITE_ITEMS" MODIFY ("UT_SID" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_SUITE_ITEMS" MODIFY ("RUN_START" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_SUITE_ITEMS" MODIFY ("RUN_TEAR" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_SUITE_ITEMS" MODIFY ("SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_SUITE_ITEMS" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_SUITE_ITEMS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
