--------------------------------------------------------
--  Ref Constraints for Table UT_TEST_IMPL_ARGUMENTS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."UT_TEST_IMPL_ARGUMENTS" ADD CONSTRAINT "UT_TEST_IMPL_ARGUMENTS_UT_FK1" FOREIGN KEY ("ARG_ID")
	  REFERENCES "HUNDISILM"."UT_TEST_ARGUMENTS" ("ARG_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "HUNDISILM"."UT_TEST_IMPL_ARGUMENTS" ADD CONSTRAINT "UT_TEST_IMPL_ARGUMENTS_UT_FK2" FOREIGN KEY ("UTI_ID")
	  REFERENCES "HUNDISILM"."UT_TEST_IMPL" ("UTI_ID") ON DELETE CASCADE ENABLE;
