--------------------------------------------------------
--  Constraints for Table UT_TEARDOWNS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."UT_TEARDOWNS" MODIFY ("TEARDOWN_ID" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEARDOWNS" MODIFY ("INDEX_NO" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEARDOWNS" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEARDOWNS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEARDOWNS" MODIFY ("UPDATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEARDOWNS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEARDOWNS" ADD CONSTRAINT "UT_TEARDOWNS_CHECK" CHECK ("TEARDOWN" IS NULL  OR "LIB_TEARDOWN_ID" IS NULL) ENABLE;
  ALTER TABLE "HUNDISILM"."UT_TEARDOWNS" ADD CONSTRAINT "UT_TEARDOWNS_PK" PRIMARY KEY ("TEARDOWN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
