--------------------------------------------------------
--  Constraints for Table UT_TEST
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."UT_TEST" MODIFY ("UT_ID" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST" MODIFY ("OBJECT_NAME" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST" MODIFY ("OBJECT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST" MODIFY ("OBJECT_OWNER" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST" ADD CONSTRAINT "UT_TEST_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HUNDISILM"."UT_TEST" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST" MODIFY ("UPDATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST" ADD CONSTRAINT "UT_TEST_PK" PRIMARY KEY ("UT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
