--------------------------------------------------------
--  Constraints for Table UT_TEST_IMPL_ARGUMENTS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."UT_TEST_IMPL_ARGUMENTS" MODIFY ("UTI_ID" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST_IMPL_ARGUMENTS" MODIFY ("ARG_ID" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST_IMPL_ARGUMENTS" MODIFY ("TEST_OUTVAL" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST_IMPL_ARGUMENTS" ADD CONSTRAINT "UT_TEST_IMPL_ARGUMENTS_PK" PRIMARY KEY ("UTI_ID", "ARG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HUNDISILM"."UT_TEST_IMPL_ARGUMENTS" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST_IMPL_ARGUMENTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST_IMPL_ARGUMENTS" MODIFY ("UPDATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST_IMPL_ARGUMENTS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
