--------------------------------------------------------
--  Constraints for Table UT_TEST_ARGUMENTS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."UT_TEST_ARGUMENTS" MODIFY ("ARG_ID" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST_ARGUMENTS" MODIFY ("OWNER" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST_ARGUMENTS" MODIFY ("OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST_ARGUMENTS" MODIFY ("POSITION" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST_ARGUMENTS" MODIFY ("SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST_ARGUMENTS" MODIFY ("DATA_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST_ARGUMENTS" ADD CONSTRAINT "UT_TEST_ARGUMENTS_PK" PRIMARY KEY ("ARG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HUNDISILM"."UT_TEST_ARGUMENTS" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST_ARGUMENTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST_ARGUMENTS" MODIFY ("UPDATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_TEST_ARGUMENTS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
