--------------------------------------------------------
--  Ref Constraints for Table UT_TEST_IMPL
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."UT_TEST_IMPL" ADD CONSTRAINT "UT_TEST_IMPL_UT_TEST_FK1" FOREIGN KEY ("UT_ID")
	  REFERENCES "HUNDISILM"."UT_TEST" ("UT_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "HUNDISILM"."UT_TEST_IMPL" ADD CONSTRAINT "UT_TEST_LIB_DYN_QUERIES_FK1" FOREIGN KEY ("LIB_DYN_QUERY_ID")
	  REFERENCES "HUNDISILM"."UT_LIB_DYN_QUERIES" ("LIB_DYN_QUERY_ID") ON DELETE CASCADE ENABLE;
