--------------------------------------------------------
--  Ref Constraints for Table UT_VALIDATIONS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."UT_VALIDATIONS" ADD CONSTRAINT "UT_VALIDATIONS_LIB_VALIDN_FK1" FOREIGN KEY ("LIB_VALIDATION_ID")
	  REFERENCES "HUNDISILM"."UT_LIB_VALIDATIONS" ("LIB_VALIDATION_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "HUNDISILM"."UT_VALIDATIONS" ADD CONSTRAINT "UT_VALIDATIONS_TEST_IMPL_FK1" FOREIGN KEY ("UTI_ID")
	  REFERENCES "HUNDISILM"."UT_TEST_IMPL" ("UTI_ID") ON DELETE CASCADE ENABLE;
