--------------------------------------------------------
--  Constraints for Table UT_VALIDATIONS
--------------------------------------------------------

  ALTER TABLE "HUNDISILM"."UT_VALIDATIONS" ADD CONSTRAINT "UT_VALIDATIONS_PK" PRIMARY KEY ("VALIDATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HUNDISILM"."UT_VALIDATIONS" ADD CONSTRAINT "UT_VALIDATIONS_CHECK" CHECK ("VALIDATION" IS NULL OR "LIB_VALIDATION_ID" IS NULL) ENABLE;
  ALTER TABLE "HUNDISILM"."UT_VALIDATIONS" MODIFY ("VALIDATION_ID" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_VALIDATIONS" MODIFY ("UTI_ID" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_VALIDATIONS" MODIFY ("INDEX_NO" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_VALIDATIONS" MODIFY ("APPLY_VALIDATION" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_VALIDATIONS" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_VALIDATIONS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_VALIDATIONS" MODIFY ("UPDATED_ON" NOT NULL ENABLE);
  ALTER TABLE "HUNDISILM"."UT_VALIDATIONS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
